---
title: 'Sex Bias in Graduate Admissions: Data from Berkeley'
author: "Malvika Rajeev"
output: html_document
---

The purpose of this paper is to demonstrate how potentially incorrect conclusions about trends can be made from the available data in certain cases where either latent variables aren’t accounted for, or if certain assumptions of the approach are actually false. In particular, the purpose is to investigate if the claim made that UC Berkeley Graduate Schools (in the fall of 1973, with approximately 12763 applicants) were biased against admitting women is valid. The morality, legality or social ramifications or the consequences that may lead to these biases is not in the statistical scope of the paper, nor does the paper claim through its conclusions that 'bias’ or 'discrimination’ can be fully understood through mere admission rates. Thus, 'bias’ is defined as a pattern of association between admission decisions and sexes of applicants. Any approach to understand the sex trends of admission is based on the **primary assumption** that for any given discipline, men and women do not differ in terms of any attribute deemed germane to their acceptance; if not, any discussion of 'sex bias’ is not meaningful.
  
    
The initial approach was to pool all the data for men and women, with the **second main assumption** that for each discipline, men and women are equally likely to apply. A contingency table of sex-wise total data led to chi square of 110.8 with 1 degree of freedom and a p-value of almost zero, which showed evidence of clear bias against women (There were ~277 fewer women than expected). (Expected admitted women = Total Admitted* Total Women that applied/Total Applied) With this conclusion, relevant departments (those that women actually applied to or which rejected women) were investigated, since each department made autonomous admission decisions. But on that granular level, most departments seem to be fair with their admission process, with 26 fewer admitted women in combined 4 departments, but also 64 fewer admitted men in a total of 6 departments.
In light of these discrepancies, the validity of the second assumption was called into question: that there is no relation between sex of applicant and the discipline applied for. It was found that the proportion of women applicants tended to be higher in departments that are 'generally harder’ to get into: i.e that had a lower admission rate. (admission rate = total accepted/total applied). So the next approach was to investigate each department individually, therefore a total of 85 independent experiments, each with their own chi square statistic. Combining these 85 statistics, according to Fisher statistic (which tests one-sided - that is alternate hyp: no bias or bias for women) and E.Scott’s method, yielded that there was **bias against men**.

At this point there are two reasons why we doubt the conclusion of first approach: no individual department has disparate admission rate, and even when we aggregate the test statistics for each department, we get found bias against men.
The reason why the sex ratios among departments is not random is because not all departments are equally easy to get into: a 2x101 contingency table of admitted vs denied applicants yielded a chi-square statistic of 2195 with a near-zero p-value. Same was corroborated through a weighted correlation test. So two key points here are that men and women have tendencies to apply for different disciplines, for example, only 2% of applicants to mechanical engineering were women, but around 2/3rds of applicants to English were women, and the ones that women applied more to had a lower admittance rate.
The next approach was to consider, one by one, the individual departments. But there were a few problems with this approach: how some departments are small so that we can’t apply approximation techniques and how when conducting 85 indivudal experiments, the chance of observing an unusual sex ratio in any one of them by chance alone (Type I error) increases.
So a final approach ('Pooling’) was introduced, which only held the first assumption and accounted for the probability of being accepted in a department and the number of women who applied in that department, to calculate the expected number of women for each department. The expected number for each department were added to get total expected admitted women. Total expected women was actually 60 fewer than observed. Using this method, data from 1969 to 1972 was also observed, indicating an absence of bias. (And if any bias, at all, it was in favour of women). The paper also discusses some perils of pooling data, such as extreme bias in different departments cancelling out.
To summarise, this paper discusses a classic case of Simspns’s paradox and found that the conclusions made from aggregated data, which doesn’t take into account non-random sex ratios among departments, are negated by more robust approaches: which found no discrimination against female applicants. According to the paper, women applied more to harder disciplines potentially because of STEM-related entrance requirements, and STEM is a field that women traditionally have been dissuaded from. The 'job market’ is also tougher for women so they tend to gravitate less towards disciplines that are more job-oriented (and thus 'easier’ to get into) Women are directed by their education and socialization toward fields that are more crowded, less productive of degrees, and less well funded and that frequently offer poorer professional employment opportunities.